version: '3'
services:
  backend:
    container_name: back_end
    image: collector:0.6.0
    ports:
      - "8100:8100"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./bin/config.json:/app/config.json

  mysql:
    container_name: project-mysql
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - ./mysql:/var/lib/mysql
